-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBcOSpwq/TPeK4GSn
Yoc3n61FZ4dWUtUe/hc7ePhRlmmgCgYIKoZIzj0DAQehRANCAARBn/oIcRuzurRq
WLrdQa8HxEHtA29YCzKJgrBITscpsXPwu59YsPzDQti90mHUvGdkj1ilC9RHIjVW
3Qsk0yHO
-----END PRIVATE KEY-----